FROM restreamio/gstreamer:$TARGET_ARCH-dev-dependencies

ARG GSTREAMER_VERSION=1.22.8

ARG GSTREAMER_CEF_REPOSITORY=https://github.com/centricular/gstcefsrc
ARG GSTREAMER_CEF_CHECKOUT=cce144d984e70cc88f4624390419171fea6ca8ee

COPY docker/cef-config.sh /.cef-config.sh

COPY docker/sccache.toml /sccache.toml

COPY docker/build-gstreamer/download /download

RUN ["/download"]

COPY docker/build-gstreamer/compile /compile
COPY docker/build-gstreamer/patch /compile-patch
