FROM ubuntu:20.04

RUN \
    apt-get update && \
    apt-get dist-upgrade -y && \
    # This allows us to easily install what is necessary for GStreamer to work
    apt-get install -y --no-install-recommends \
        gstreamer1.0-plugins-bad \
        gstreamer1.0-plugins-base \
        gstreamer1.0-plugins-good \
        gstreamer1.0-plugins-ugly \
        gstreamer1.0-libav \
        gstreamer1.0-nice \
        ladspa-sdk \
        libxv1 && \
    # However, we don't need GStreamer itself and its plugins, since we've just built them from source
    apt-get remove -y --purge \
        gstreamer1.0-plugins-bad \
        gstreamer1.0-plugins-base \
        gstreamer1.0-plugins-good \
        gstreamer1.0-plugins-ugly \
        gstreamer1.0-libav \
        gstreamer1.0-nice \
        libgstreamer-plugins-bad1.0-0 \
        libgstreamer-plugins-base1.0-0 \
        libgstreamer-plugins-good1.0-0 \
        libgstreamer1.0-0 \
        libusrsctp1 \
        libnice10 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
