FROM restreamio/gstreamer:latest-dev-dependencies

ARG GSTREAMER_REPOSITORY=https://gitlab.freedesktop.org/gstreamer/gstreamer.git
ARG GSTREAMER_CHECKOUT=333b77bc9fa5d8b7f592b63eac4d77cdcb92a280

ARG USRSCTP_REPOSITORY=https://github.com/sctplab/usrsctp.git
ARG USRSCTP_CHECKOUT=83dcca61125fce4c94d1279659c9dae07434f469

ARG LIBNICE_REPOSITORY=https://gitlab.freedesktop.org/libnice/libnice.git
ARG LIBNICE_CHECKOUT=a9c2846a89c4e74efbd7ef59fcfe7ff05efb2c5e

ARG GST_PLUGINS_BASE_REPOSITORY=https://gitlab.freedesktop.org/gstreamer/gst-plugins-base.git
ARG GST_PLUGINS_BASE_CHECKOUT=637bbac62245d836490a1e755a2c0272a66b640e

ARG GST_PLUGINS_BAD_REPOSITORY=https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad.git
ARG GST_PLUGINS_BAD_CHECKOUT=b2666520433ec6257827bba7bba55e6387039b1a

ARG GST_PLUGINS_GOOD_REPOSITORY=https://gitlab.freedesktop.org/nazar-pc/gst-plugins-good.git
ARG GST_PLUGINS_GOOD_CHECKOUT=b410ebec58f153f6880f4645676880e09e3aeb35

ARG GST_PLUGINS_UGLY_REPOSITORY=https://gitlab.freedesktop.org/gstreamer/gst-plugins-ugly.git
ARG GST_PLUGINS_UGLY_CHECKOUT=8fe8ed3dd2bdcf22097d9886ad5242258b64ee44

ARG GST_LIBAV_REPOSITORY=https://gitlab.freedesktop.org/gstreamer/gst-libav.git
ARG GST_LIBAV_CHECKOUT=e727ce548c28e5a0577148069a7a81f67b9ba630

COPY docker/build-gstreamer/download /

RUN ["/download"]

COPY docker/build-gstreamer/compile /
