FROM ubuntu:26.04

ARG DEBIAN_FRONTEND=noninteractive

RUN \
    apt-get update && \
    apt-get dist-upgrade -y && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        libatk1.0-0t64 \
        libatk-bridge2.0-0t64 \
        libatk-adaptor \
        libatspi2.0-0t64 \
        libunwind8 \
        libdw1t64 \
        libgmp10 \
        libgsl28 \
        libglib2.0-0t64 \
        libcap2 \
        libcups2t64 \
        liborc-0.4-0t64 \
        iso-codes \
        libgl1 \
        libgles1 \
        libgles2 \
        libgudev-1.0-0 \
        libgbm1 \
        libgraphene-1.0-dev \
        libpng16-16t64 \
        libjpeg8 \
        libogg0 \
        libopus0 \
        libpango-1.0-0 \
        libvisual-0.4-0 \
        libtheora1 \
        libvorbis0a \
        libxkbcommon0 \
        libxcomposite1 \
        libxdamage1 \
        libwayland-client0 \
        libwayland-cursor0 \
        libwayland-egl1 \
        libwayland-server0 \
        libharfbuzz-icu0 \
        libegl1 \
        libepoxy0 \
        libgcrypt20 \
        libwebp7 \
        libwebpdemux2 \
        libwebpmux3 \
        libopenjp2-7 \
        libwoff1 \
        libxslt1.1 \
        bubblewrap \
        libseccomp2 \
        xdg-dbus-proxy \
        libsoup-3.0-0 \
        libvulkan1 \
        libass9 \
        libchromaprint1 \
        libcurl3t64-gnutls \
        libaom3 \
        libbz2-1.0 \
        liblcms2-2 \
        libbs2b0 \
        libdca0 \
        libfaac0t64 \
        libfaad2 \
        libflite1 \
        libssl3t64 \
        ladspa-sdk \
        libfdk-aac2 \
        libgsm1 \
        libkate1 \
        libgme0 \
        libde265-0 \
        liblilv-0-0 \
        libmodplug1 \
        mjpegtools \
        libmjpegutils-2.2-0 \
        libmpcdec6 \
        libdvdnav4 \
        libdvdread8t64 \
        librsvg2-2 \
        librtmp1 \
        libsbc1 \
        libsndfile1 \
        libsoundtouch1 \
        libspandsp2t64 \
        libsrt1.5-openssl \
        libsrtp2-1 \
        libvo-aacenc0 \
        libvo-amrwbenc0 \
        libwebrtc-audio-processing-1-3 \
        libwebrtc-audio-coding-1-3 \
        libofa0 \
        libzvbi0t64 \
        libopenexr-3-1-30 \
        libwildmidi2 \
        libx265-215 \
        libzbar0t64 \
        wayland-protocols \
        libaa1 \
        libmp3lame0 \
        libcaca0 \
        libdv4t64 \
        libmpg123-0t64 \
        libvpx12 \
        libshout3 \
        libspeex1 \
        libtag2 \
        libtwolame0 \
        libwavpack1 \
        liba52-0.7.4 \
        libx264-165 \
        libopencore-amrnb0 \
        libopencore-amrwb0 \
        libmpeg2-4 \
        libavcodec62 \
        libavfilter11 \
        libavformat62 \
        libavutil60 \
        libva2 \
        libva-wayland2 \
        xvfb \
        libxrandr-dev \
        glibc-tools

COPY docker/install-arch-specific-dependencies.sh /.install-deps.sh
RUN /.install-deps.sh

# Add 'render' group to allow access to /dev/dri/renderD128
# To have access to the Intel GPU through libva for hardware acceleration,
# running user must be in the 'video' and 'render' groups.
RUN \
    rm -f /.install-deps.sh && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    groupadd -f -g 110 render
