FROM restreamio/gstreamer:$TARGET_ARCH-dev-dependencies

ARG GSTREAMER_REPOSITORY=https://gitlab.freedesktop.org/philn/gstreamer.git

# 1.20-studio-rebase-220504 branch
ARG GSTREAMER_CHECKOUT=3cbbd3addcf5dd1f88ab595a5562d16ee975c35d

ARG GSTREAMER_CEF_REPOSITORY=https://github.com/SoftwareArchitector/gstcefsrc
# fix/pts: audio/video pts improvements
ARG GSTREAMER_CEF_CHECKOUT=85121b58d7b59cc33ee4f9f6bba1db1d22a29eb3

COPY docker/cef-config.sh /.cef-config.sh

COPY docker/sccache.toml /sccache.toml

COPY docker/build-gstreamer/download /download

RUN ["/download"]

COPY docker/build-gstreamer/compile /compile
