FROM restreamio/gstreamer:dev-dependencies

ARG GSTREAMER_REPOSITORY=https://gitlab.freedesktop.org/nazar-pc/gstreamer.git
ARG GSTREAMER_CHECKOUT=10e593be7424bfdccc346098efccb3a64cba7b3c

ARG LIBWPE_VERSION=1.9.1
ARG WPEBACKEND_FDO_VERSION=1.9.1
ARG WPEWEBKIT_VERSION=2.31.91

ARG LIBNICE_REPOSITORY=https://gitlab.freedesktop.org/libnice/libnice.git
ARG LIBNICE_CHECKOUT=36aa468c4916cfccd4363f0e27af19f2aeae8604

ARG GST_PLUGINS_BASE_REPOSITORY=https://gitlab.freedesktop.org/nazar-pc/gst-plugins-base.git
ARG GST_PLUGINS_BASE_CHECKOUT=4aaf0d258e315b036f4f583848996c0548900af7

ARG GST_PLUGINS_BAD_REPOSITORY=https://gitlab.freedesktop.org/nazar-pc/gst-plugins-bad.git
ARG GST_PLUGINS_BAD_CHECKOUT=2b7b1b2911480755c46ab14364c32fe3fe378bb0

ARG GST_PLUGINS_GOOD_REPOSITORY=https://gitlab.freedesktop.org/nazar-pc/gst-plugins-good.git
ARG GST_PLUGINS_GOOD_CHECKOUT=9d4c6ee42464992a74d9c391dfbed8da1a15beb6

ARG GST_PLUGINS_UGLY_REPOSITORY=https://gitlab.freedesktop.org/gstreamer/gst-plugins-ugly.git
ARG GST_PLUGINS_UGLY_CHECKOUT=6399179d7a2e51e5d9b159986104d733464180f9

ARG GST_LIBAV_REPOSITORY=https://gitlab.freedesktop.org/gstreamer/gst-libav.git
ARG GST_LIBAV_CHECKOUT=1b81e05ab9203fead9fbca4997703b2ed6484ec2

ARG GSTREAMER_VAAPI_REPOSITORY=https://gitlab.freedesktop.org/gstreamer/gstreamer-vaapi.git
ARG GSTREAMER_VAAPI_CHECKOUT=d270654c48c19afc3234e126269bf613540b44d8

COPY docker/build-gstreamer/download /

RUN ["/download"]

COPY docker/build-gstreamer/compile /
