FROM restreamio/gstreamer:$TARGET_ARCH-dev-dependencies

ARG GSTREAMER_VERSION=1.22.12

ARG GSTREAMER_CEF_REPOSITORY=https://github.com/centricular/gstcefsrc
ARG GSTREAMER_CEF_CHECKOUT=b63340852fc93b0ab67b07200e1ff44f59ba6769

COPY docker/cef-config.sh /.cef-config.sh

COPY docker/sccache.toml /sccache.toml

COPY docker/build-gstreamer/download /download

RUN ["/download"]

COPY docker/build-gstreamer/compile /compile
COPY docker/build-gstreamer/patch /compile-patch
