[dist]
scheduler_url = "@@SCCACHE_SCHEDULER@@"

[dist.auth]
type = "token"
token = "@@SCCACHE_AUTH_TOKEN@@"

[[dist.toolchains]]
type = "path_override"
compiler_executable = "/usr/bin/clang"
archive = "/toolchain-clang-12.tar.gz"
archive_compiler_executable = "/usr/bin/clang-12"

[[dist.toolchains]]
type = "path_override"
compiler_executable = "/usr/bin/clang++"
archive = "/toolchain-clang-12.tar.gz"
archive_compiler_executable = "/usr/bin/clang-12"
