#!/bin/bash
set -e

git clone -b "$GSTREAMER_VERSION" https://gitlab.freedesktop.org/gstreamer/gstreamer.git

source /.cef-config.sh
git clone --no-checkout "$CEF_REPOSITORY"
pushd gstcefsrc
git checkout "$CEF_CHECKOUT"
popd
