#!/bin/bash
set -e

git clone -b "$GSTREAMER_VERSION" https://gitlab.freedesktop.org/gstreamer/gstreamer.git

git clone --no-checkout "$GSTREAMER_CEF_REPOSITORY"
pushd gstcefsrc
git checkout "$GSTREAMER_CEF_CHECKOUT"
popd
