#!/bin/bash
set -e

export DEBIAN_FRONTEND=noninteractive

sed -i 's/# deb-src/deb-src/g' /etc/apt/sources.list
apt-get update
apt-get dist-upgrade -y
apt-get install -y --no-install-recommends \
  ca-certificates \
  ffmpeg \
  git \
  meson \
  ninja-build
apt-get build-dep -y \
  gstreamer1.0 \
  gstreamer1.0-plugins-{bad,base,good,ugly} \
  gstreamer1.0-{libav,nice}
# These are not needed for build and will sometimes conflict with things we build
apt-get remove -y --autoremove --purge \
  gstreamer1.0-doc \
  gstreamer1.0-plugins-base \
  gstreamer1.0-plugins-base-doc \
  gstreamer1.0-libav \
  gir1.2-gst-plugins-base-1.0 \
  gir1.2-gstreamer-1.0 \
  libgstreamer-gl1.0-0 \
  libgstreamer-plugins-base1.0-0 \
  libgstreamer-plugins-base1.0-dev \
  libgstreamer-plugins-good1.0-0 \
  libgstreamer-plugins-good1.0-dev \
  libgstreamer1.0-0 \
  libgstreamer1.0-dev \
  libnice10
apt-get clean
rm -rf /var/lib/apt/lists/*
