# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    resource_class: 2xlarge
    steps:
      - setup_remote_docker:
          version: 20.10.12
      - checkout
      - run:
          name: "Login to dockerhub"
          command: "echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin"
      - run:
          name: "Build images"
          command: "./build-latest.sh"
      - run:
          name: "Push images"
          command: "./push-latest.sh"

workflows:
  build-workflow:
    jobs:
      - build
