# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# TODO: arm64 build jobs.

jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: "Login to dockerhub"
          command: "echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin"
      - run:
          name: "Build images"
          command: "./build-latest.sh amd64"
      - run:
          name: "Push images"
          command: "./push-latest.sh amd64"

workflows:
  build-workflow:
    jobs:
      - build
