name: Docker Build Workflow

on:
  push:
    branches:
    - master

  pull_request:
    branches:
    - master

concurrency:
  group: ${{ github.event.repository.name }}-ci-${{ github.event.pull_request.number }}
  cancel-in-progress: true

env:
  WORKING_DIR: /tmp/docker-gst-ci

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up workspace
      run: mkdir -p ${{ env.WORKING_DIR }}/workspace

    - name: Save current date as environment variable
      run: echo "DATE=$(date -u +"%Y-%m-%dT%H-%M-%SZ")" > ${{ env.WORKING_DIR }}/workspace/env-vars

    - name: Upload workspace artifact
      uses: actions/upload-artifact@v4
      with:
        name: workspace
        path: ${{ env.WORKING_DIR }}/workspace

  amd64-build:
    needs: init
    runs-on: ubuntu-amd64-8core
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download workspace artifact
      uses: actions/download-artifact@v4
      with:
        name: workspace
        path: workspace

    - name: Load environment variables
      run: source workspace/env-vars

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_LOGIN }}
        password: ${{ secrets.DOCKER_PWD }}

    - name: Build AMD64 image
      run: ./build-latest.sh

    - name: Push AMD64 image
      run: ./push-latest.sh

    - name: Upload AMD64 docker tag
      uses: actions/upload-artifact@v4
      with:
        name: workspace
        path: workspace

  arm64-build:
    needs: init
    runs-on: ubuntu-arm64-8core
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download workspace artifact
      uses: actions/download-artifact@v4
      with:
        name: workspace
        path: workspace

    - name: Load environment variables
      run: source workspace/env-vars

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_LOGIN }}
        password: ${{ secrets.DOCKER_PWD }}

    - name: Build ARM64 image
      run: ./build-latest.sh

    - name: Push ARM64 image
      run: ./push-latest.sh

    - name: Upload ARM64 docker tag
      uses: actions/upload-artifact@v4
      with:
        name: workspace
        path: workspace

  aggregate-images:
    needs:
    - amd64-build
    - arm64-build
    runs-on: ubuntu-amd64-8core
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download workspace artifact
      uses: actions/download-artifact@v4
      with:
        name: workspace
        path: workspace

    - name: Load environment variables
      run: source workspace/env-vars

    - name: Verify AMD64 and ARM64 tags
      run: |
        cat workspace/docker-tag-basename-x86_64.txt
        cat workspace/docker-tag-basename-aarch64.txt

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_LOGIN }}
        password: ${{ secrets.DOCKER_PWD }}

    - name: Push multi-architecture Docker images
      run: ./push-multi-arch-latest.sh
